config/routes.rb
Rails.application.routes.draw do
  resources :user_games do
    get '/get_from_code/:code', to: 'user_games#get_from_code', on: :collection
  end


  authenticated :user do
    root to: 'home#index'
  end

  unauthenticated :user do
    devise_scope :user do
      get '/', to: 'devise/sessions#new'

      get '/cadastro/aluno', to: 'users/registrations#new', role: :student, as: :new_student
      get '/cadastro/professor', to: 'users/registrations#new', role: :professor, as: :new_professor
    end
  end

  devise_for :users, controllers: { registrations: 'users/registrations' }

  devise_scope :user do
    get :sair, to: 'devise/sessions#destroy'
  end

  # GAME

  namespace :game do
    post '/user_game',                                          to: 'user_games#create',   defaults: { format: :json }
    get '/user_game/me/:code',                                  to: 'user_games#me',   defaults: { format: :json }

    get '/',                                                                          to: 'modulos#index',          defaults: { format: :json }, as: :modulos
    get '/all',                                                                       to: 'modulos#all',            defaults: { format: :json }, as: :all
    get '/:modulo_slug',                                                              to: 'target_audiences#index', defaults: { format: :json }, as: :target_audiences
    get '/:modulo_slug/:target_audience_slug',                                        to: 'themes#index',           defaults: { format: :json }, as: :themes
    get '/:modulo_slug/:target_audience_slug/:theme_slug',                            to: 'units#index',            defaults: { format: :json }, as: :units
    get '/:modulo_slug/:target_audience_slug/:theme_slug/:unit_slug',                 to: 'questions#index',        defaults: { format: :json }, as: :questions
    get '/:modulo_slug/:target_audience_slug/:theme_slug/:unit_slug/:question_order', to: 'questions#show',         defaults: { format: :json }, as: :question
  end

  # GAME

  namespace :question do
    resources :types
    resources :item_templates
    resources :titles
    resources :descriptions
    resources :templates, controller: 'question_templates' do
      get :list, on: :collection
    end

    resources :questions do
      put :publish, on: :member
      put :archive, on: :member
      resources :items, controller: 'questions_items'
    end
  end

  resources :themes do
    resources :units
  end
  resources :units
  resources :theme_audiences
  resources :modulos
  resources :groups do
    resources :participants, controller: :groups_participants
  end

  resources :words
  resources :karaokes
  resources :books

  namespace :admin do
    resources :users
  end

  namespace :professor do
    resources :students
  end

  get '/pages/*id' => 'pages#show', as: :page, format: false
end

app/views/layouts/sb-admin-2/_navbar.html.slim
nav.ld-navbar.navbar.navbar-default.navbar-fixed-top[role="navigation"]
  .container-fluid
    .navbar-header
      a.navbar-brand.aside-toggle [href="#"]
        i.icon.icon--is-dark.icon-bars-solid

      = link_to root_url, class: 'navbar-brand' do
        = image_tag 'logo.svg'

    ul.ld-navbar-profile.nav.navbar-nav.navbar-right
      li.dropdown
        a.dropdown-toggle[data-toggle="dropdown" href="#"]
          i.icon.icon-user-circle-solid.fa-2x
          i.fa.fa-caret-down

        ul.dropdown-menu.dropdown-user
          li
            = link_to edit_user_registration_path do
              i.fa.fa-user.fa-fw
              |  Perfil 
              = "(#{current_user.role_i18n})"

          li.divider

          li
            = link_to destroy_user_session_url, method: :delete do
              i.fa.fa-sign-out.fa-fw
              |  Sair

aside [aria-expanded="false"]
  .navbar.sidebar[role="navigation"]
    = render "layouts/sb-admin-2/sidebar-links"

app/views/layouts/sb-admin-2/_sidebar-links.html.slim
.list-group
  - if current_user.admin?
    = link_to admin_users_path, class: 'list-group-item' do
      i.icon.icon-user-solid.fa-lg
      |  Usuários

  - if current_user.admin?
    = link_to themes_path, class: 'list-group-item' do
      i.icon.icon-pen-solid.fa-lg
      ' Temas

  / li
  /   = link_to units_path do
  /     i.fa.fa-bookmark.fa-fw
  /     ' Unidades

  - if current_user.admin? || current_user.professor?
    = link_to groups_path, class: 'list-group-item' do
      i.icon.icon-users-solid.fa-lg
      ' Turmas

  - if current_user.admin? || current_user.professor?
    = link_to question_questions_url, class: 'list-group-item' do
      i.icon.icon-clipboard-list-solid.fa-lg
      |  Atividades

    / a[class="list-group-item" role="button" data-toggle="collapse" href="#subMenuAtividades" aria-expanded="false" aria-controls="subMenuAtividades"]
    /   i.icon.icon-clipboard-list-solid.fa-lg
    /   |  Atividades
    /   span.fa.arrow
    / .collapse#subMenuAtividades
    /   = link_to question_templates_url, class: 'list-group-item' do
    /     / i.fa.fa-edit.fa-fw
    /     ' Cadastrar
    /
    /   = link_to question_questions_url, class: 'list-group-item' do
    /     / i.fa.fa-book.fa-fw
    /     ' Lista

  - if current_user.admin?
    a[class="list-group-item" role="button" data-toggle="collapse" href="#subMenuBasicos" aria-expanded="false" aria-controls="subMenuBasicos"]
      i.icon.icon-plus-solid.fa-lg
      |  Cadastros Básicos
      span.fa.arrow
    .collapse#subMenuBasicos
      = link_to words_url, class: 'list-group-item' do
        / i.fa.fa-pencil.fa-fw
        ' Elementos(Letras, Sílabas, Palavras..)
      = link_to question_descriptions_url, class: 'list-group-item' do
        / i.fa.fa-pencil.fa-fw
        ' Enunciados
      = link_to list_question_templates_url, class: 'list-group-item' do
        / i.fa.fa-pencil.fa-fw
        ' Templates
      = link_to karaokes_url, class: 'list-group-item' do
        / i.fa.fa-pencil.fa-fw
        ' Karaokê

      / = link_to question_item_templates_url, class: 'list-group-item' do
      /   / i.fa.fa-edit.fa-fw
      /   ' Template de Item


    a[class="list-group-item" role="button" data-toggle="collapse" href="#subGames" aria-expanded="false" aria-controls="subGames"]
      i.icon.icon-gamepad-solid.fa-lg
      |  Games
      span.fa.arrow

    .collapse#subGames
      = link_to 'http://luz-do-saber-portal-staging.herokuapp.com', class: 'list-group-item', target: '_blank' do
        ' Home Page

      = link_to 'Jogos', user_games_url, class: 'list-group-item'

  - if current_user.professor?
    = link_to professor_students_path, class: 'list-group-item' do
      i.icon.icon-user-solid.fa-lg
      |  Alunos
  - if current_user.admin?
    = link_to books_path, class: 'list-group-item'
      i.icon.icon-book-solid.fa-lg
      |  Livros
  - if current_user.admin?
    = link_to user_games_url, class: 'list-group-item'
      i.icon.icon-users-solid.fa-lg
      |  Histórico