config/routes.rb
Rails.application.routes.draw do
  resources :user_games do
    get '/get_from_code/:code', to: 'user_games#get_from_code', on: :collection
  end


  authenticated :user do
    root to: 'home#index'
  end

  unauthenticated :user do
    devise_scope :user do
      get '/', to: 'devise/sessions#new'

      get '/cadastro/aluno', to: 'users/registrations#new', role: :student, as: :new_student
      get '/cadastro/professor', to: 'users/registrations#new', role: :professor, as: :new_professor
    end
  end

  devise_for :users, controllers: { registrations: 'users/registrations' }

  devise_scope :user do
    get :sair, to: 'devise/sessions#destroy'
  end

  # GAME

  namespace :game do
    post '/user_game',                                          to: 'user_games#create',   defaults: { format: :json }
    get '/user_game/me/:code',                                  to: 'user_games#me',   defaults: { format: :json }

    get '/',                                                                          to: 'modulos#index',          defaults: { format: :json }, as: :modulos
    get '/all',                                                                       to: 'modulos#all',            defaults: { format: :json }, as: :all
    get '/:modulo_slug',                                                              to: 'target_audiences#index', defaults: { format: :json }, as: :target_audiences
    get '/:modulo_slug/:target_audience_slug',                                        to: 'themes#index',           defaults: { format: :json }, as: :themes
    get '/:modulo_slug/:target_audience_slug/:theme_slug',                            to: 'units#index',            defaults: { format: :json }, as: :units
    get '/:modulo_slug/:target_audience_slug/:theme_slug/:unit_slug',                 to: 'questions#index',        defaults: { format: :json }, as: :questions
    get '/:modulo_slug/:target_audience_slug/:theme_slug/:unit_slug/:question_order', to: 'questions#show',         defaults: { format: :json }, as: :question
  end

  # GAME

  namespace :question do
    resources :types
    resources :item_templates
    resources :titles
    resources :descriptions
    resources :templates, controller: 'question_templates' do
      get :list, on: :collection
    end

    resources :questions do
      put :publish, on: :member
      put :archive, on: :member
      resources :items, controller: 'questions_items'
    end
  end

  resources :themes do
    resources :units
  end
  resources :units
  resources :theme_audiences
  resources :modulos
  resources :groups do
    resources :participants, controller: :groups_participants
  end

  resources :words
  resources :karaokes
  resources :books

  namespace :admin do
    resources :users
  end

  namespace :professor do
    resources :students
  end

  get '/pages/*id' => 'pages#show', as: :page, format: false
end

app/models/concerns/question/item_word_helper.rb
require 'active_support/concern'

module Question::ItemWordHelper
  extend ActiveSupport::Concern

  private

  # O item da atividade indica como a palavra sera gerada.
  # Mesmo indicado um source a customizacao tem prioridade.
  def find_a_word(keys:, values:, external_words:)
    if custom_item
      word_from_custom custom: custom_item, keys: keys, values: values, external_words: external_words
    else
      # Encontra uma palavra.
      word_from_source keys: keys, values: values, external_words: external_words
    end
  end

  # Total de itens com palavras definidas.
  def total_items(keys, values)
    case type
    when 'key' then keys.select { |i| i.word.present? }.count
    when 'value' then values.select { |i| i.word.present? }.count
    end
  end

  # Textos ja definidos nos itens.
  def already_used_texts(keys, values)
    texts = [keys, values].flatten.map do |i|
      i.try(:word).try(:text)
    end.compact.uniq

    # Para nao invalidar a busca no banco de dados com NULL.
    return [''] if texts.empty?

    texts
  end
end

app/models/question.rb
module Question
  def self.table_name_prefix
    'question_'
  end
end

app/models/question/description.rb
# Descricao de uma questao.
class Question::Description < ApplicationRecord
  self.inheritance_column = :_type_disabled

  enum type: {
    texto: 0,
    subtitle: 1
  }

  # belongs_to :question, foreign_key: :question_question_id, class_name: 'Question::Question'

  before_validation -> { self.text = self.text.upcase }

  validates :text, presence: true

  has_attached_file :audio
  validates_attachment_content_type :audio, content_type: /\Aaudio\/.*\z/

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  before_create :set_default_remote_audio_url, unless: -> { audio.present? }
  before_validation :lowercase_filename

  #nomes em minusculo
  def lowercase_filename
    if image.present?
      n = image_file_name.downcase
      self.image_file_name = n
    end
    if audio.present?
      n = audio_file_name.downcase
      self.audio_file_name = n
    end
  end

  def audio_full_url
    if audio.present?
      audio.url
    else
      remote_audio_url
    end
  end

  def image_full_url
    if image.present?
      [ENV['ASSET_HOST'], image.url].join('/')
    else
      remote_image_url
    end
  end

  private

  def set_default_remote_audio_url
    audio_path = ['audios', 'enunciados', "#{text.parameterize}.mp3"].join('/')

    self.remote_audio_url = [ENV['ASSET_HOST'], audio_path].join('/')
  end
end

app/controllers/game/questions_controller.rb
# Atividades de uma unidade.
class Game::QuestionsController < ApplicationController
  skip_before_action :authenticate_user!

  before_action :set_unit

  def index
    @questions = if params[:group_code].present?
                    policy_scope(@unit.questions.by_group(params[:group_code]))
                  else
                    policy_scope(@unit.questions.joins(:user).where(users: { role: User.roles['admin'] }))
                  end.order(:order)
  end

  def show
    # Algumas questoes necessitam de um parametro externo com um nome.
    @external_words,
    # Itens KEY independentes de parametro externo.
    @keys,
    # Itens VALUE independentes de parametro externo.
    @values = [], [], []

    @question = policy_scope(@unit.questions).find_by!(order: params[:question_order])

    set_external_words if !@question.external_param_nenhum? && params[:external_params].present?

    # Itens independentes de parametros externos.
    set_words_to_items

    # Questoes como parametros externos podem ter itens que nao serao utilizados.
    #
    # Ex.: Questoes que recebem parametros externos tem 12 itens, mas o nome do usuario pode ocupar apenas 6.
    #      Os itens sem informacao nao devem ser exibidos.
    clean_items

  rescue => e
    render json: { error: e.message }, status: :not_found
  end

  private

  def set_unit
    @target_audience = ThemeAudience.friendly.find(params[:target_audience_slug])
    @theme = Theme.where(:theme_audience_id => @target_audience).friendly.find(params[:theme_slug])
    @unit = Unit.where(:theme=> @theme).joins(:theme).friendly.find(params[:unit_slug])
  end

  # Remove itens sem informacao e embaralha as chaves e valores.
  def clean_items
    clean_key_items
    clean_value_items
  end

  def clean_key_items
    @keys = @keys.select { |k,_| k.word.try(:text).present? }
    @keys = @keys.to_a.shuffle if @question.shuffle_key_items
  end

  def clean_value_items
    @values = @values.select { |k,_| k.word.try(:text).present? }
    @values = @values.to_a.shuffle if @question.shuffle_value_items
  end

  # Itens que nao dependem de parametro externo.
  def set_words_to_items
    # Seta itens KEY independentes de parametros externos.
    set_words_to_key_items if @question.items.key.any?

    # Seta itens VALUE independentes de parametros externos.
    set_words_to_value_items if @question.items.value.any?
  end

  def set_words_to_key_items
    # Items tipo key desta atividade.
    @keys = @question.items.key.order(:id)

    # O item informa como ele deve ser criado.
    @keys.each { |item| item.set_word_from_source keys: @keys, values: @values, external_words: @external_words }
  end

  def set_words_to_value_items
    # Items tipo value desta atividade.
    @values = @question.items.value.order(:key_id, :id)

    # O item informa como ele deve ser criado.
    @values.each { |item| item.set_word_from_source keys: @keys, values: @values, external_words: @external_words }
  end

  # external_params = [
  #   {
  #     name: 'FULANO',
  #     image: 'IMAGE_URL'
  #   }, {...}
  # ]
  #
  # Se a questao necessita de parametros externos mas nao recebe, estes devem ser gerados usando o banco.
  def set_external_words
    # Transforma os parametros recebidos em um Hash.
    external_params = params.require(:external_params).permit!.to_h

    # Se a quantidade de parametros recebidos for menor que a necessaria, o Hash
    # deve ser completado com palavras do banco.
    unless external_params.length == @question.external_param_total
      (external_params.length..@question.external_param_total).each do |ep|
        # Completa o array de palavras externas com palavras do mesmo tipo.
        external_params[ep] = { name: Word.where(type: @question.external_param_type).sample.text }
      end
    end

    # Cria um array de palavras (Word) com os parametros recebidos.
    external_params.each do |k, word|
      # Inicializa uma palavra do tipo que a questao pede com o texto passado.
      w = Word.new type: @question.external_param_type, text: word['name']

      # Se uma URL de imagem foi passado como parametro.
      w.images << WordImage.new(external_param_image_url: word['image']) if word['image'].present?

      # Seta informacoes adicionais as palavras.
      w.set_info_data

      @external_words << w
    end
  end
end

app/controllers/question/descriptions_controller.rb
class Question::DescriptionsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_question_description, only: [:show, :edit, :update, :destroy]

  # GET /question/descriptions
  def index
    @q = Question::Description.ransack(params[:q])
    respond_to do |format|
      format.html { @descriptions = @q.result.order(:text).page(params[:page]) }
      format.json { @descriptions = @q.result.order(:text) }
    end
  end

  # GET /question/descriptions/1
  def show
  end

  # GET /question/descriptions/new
  def new
    @description = Question::Description.new
  end

  # GET /question/descriptions/1/edit
  def edit
  end

  # POST /question/descriptions
  def create
    @description = Question::Description.new(question_description_params)


    respond_to do |format|
      if @description.save
        format.json { render json: @description }
        format.html { redirect_to @description, notice: t('helpers.submit.saved') }
      else
        respond_to do |format|
          format.json { render json: { errors: @description.errors } }
          format.html { render :new }
        end
      end
    end
  end

  # PATCH/PUT /question/descriptions/1
  def update
    if @description.update(question_description_params)
      redirect_to @description, notice: t('helpers.submit.saved')
    else
      render :edit
    end
  end

  # DELETE /question/descriptions/1
  def destroy
    @description.destroy
    redirect_to question_descriptions_url, notice: t('helpers.submit.saved')
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_question_description
    @description = Question::Description.find(params[:id])
    if @description.image_file_name.present?
      n = @description.image_file_name.downcase
      @description.image_file_name = n
    end
    if @description.audio_file_name.present?
      n = @description.audio_file_name.downcase
      @description.audio_file_name = n 
    end
  end

  # Only allow a trusted parameter "white list" through.
  def question_description_params
    params.require(:question_description).permit(:question_question_id, :type, :text, :image, :audio)
  end
end

app/controllers/question/item_templates_controller.rb
class Question::ItemTemplatesController < ApplicationController
  before_action :set_question_item_template, only: [:show, :edit, :update, :destroy]

  # GET /question/item_templates
  def index
    @item_templates = Question::ItemTemplate.all
  end

  # GET /question/item_templates/1
  def show
  end

  # GET /question/item_templates/new
  def new
    @item_template = Question::ItemTemplate.new
  end

  # GET /question/item_templates/1/edit
  def edit
  end

  # POST /question/item_templates
  def create
    @item_template = Question::ItemTemplate.new(question_item_template_params)

    if @item_template.save
      redirect_to @item_template, notice: t('helpers.submit.saved')
    else
      render :new
    end
  end

  # PATCH/PUT /question/item_templates/1
  def update
    if @item_template.update(question_item_template_params)
      redirect_to @item_template, notice: t('helpers.submit.saved')
    else
      render :edit
    end
  end

  # DELETE /question/item_templates/1
  def destroy
    @item_template.destroy
    redirect_to question_item_templates_url, notice: t('helpers.submit.destroyed')
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_question_item_template
    @item_template = Question::ItemTemplate.friendly.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def question_item_template_params
    params.require(:question_item_template).permit(:type,
                                                   :name,
                                                   :description,
                                                   :total_per_line,
                                                   :image,
                                                   :delete_image)
  end
end

app/controllers/question/question_templates_controller.rb
class Question::QuestionTemplatesController < ApplicationController
  before_action :set_question_template, only: [:show, :edit, :update, :destroy]

  # GET /question/question_templates
  # GET /question/question_templates.json
  def index
    @question_templates = Question::QuestionTemplate.order(:name)
  end

  def list
    @question_templates = Question::QuestionTemplate.order(:name)
  end

  # GET /question/question_templates/1
  # GET /question/question_templates/1.json
  def show
  end

  # GET /question/question_templates/new
  def new
    @question_template = Question::QuestionTemplate.new
  end

  # GET /question/question_templates/1/edit
  def edit
  end

  # POST /question/question_templates
  # POST /question/question_templates.json
  def create
    @question_template = Question::QuestionTemplate.new(question_question_template_params)

    if @question_template.save
      redirect_to question_template_url(@question_template), notice: t('helpers.submit.saved')
    else
      render :new
    end
  end

  # PATCH/PUT /question/question_templates/1
  # PATCH/PUT /question/question_templates/1.json
  def update
    if @question_template.update(question_question_template_params)
      redirect_to question_template_url(@question_template), notice: t('helpers.submit.saved')
    else
      render :edit
    end
  end

  # DELETE /question/question_templates/1
  # DELETE /question/question_templates/1.json
  def destroy
    @question_template.destroy

    redirect_to question_templates_url, notice: t('helpers.submit.destroyed')
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_question_template
    @question_template = Question::QuestionTemplate.friendly.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def question_question_template_params
    params.require(:question_question_template).permit(:name,
                                                        :image,
                                                        :question_type,
                                                        :question_subtype,
                                                        :question_description,
                                                        :question_title,

                                                        :question_external_param_type,
                                                        :question_external_param_total,

                                                        :question_total_correct_items,
                                                        :question_shuffle_keys,
                                                        :question_shuffle_values,

                                                        :points_lost_a_star_by_attempt,
                                                        :points_lost_a_star_by_time,

                                                        :item_template_key_font_size,
                                                        :item_template_key_custom,
                                                        :item_template_key_tags,
                                                        :item_template_key_total_per_line,
                                                        :item_template_key_template_slug,
                                                        :item_template_value_font_size,
                                                        :item_template_value_custom,
                                                        :item_template_value_tags,
                                                        :item_template_value_total_per_line,
                                                        :item_template_value_template_slug)
  end
end

app/views/question/question_templates/_form.html.slim
- url = @question_template.new_record? ? question_templates_path : question_template_path(@question_template)

= simple_form_for @question_template, url: url do |f|
  = f.input :name
  = f.input :image
  = f.input :question_description
  = f.input :question_title
  = f.input :question_type
  = f.input :question_subtype
  = f.input :question_total_correct_items
  = f.input :question_shuffle_keys
  = f.input :question_shuffle_values
  = f.input :points_lost_a_star_by_attempt
  = f.input :points_lost_a_star_by_time
  = f.input :item_template_key_font_size
  = f.input :item_template_key_custom
  = f.input :item_template_key_tags
  = f.input :item_template_key_total_per_line
  = f.input :item_template_key_template_slug
  = f.input :item_template_value_font_size
  = f.input :item_template_value_custom
  = f.input :item_template_value_tags
  = f.input :item_template_value_total_per_line
  = f.input :item_template_value_template_slug

  .row
    .col-lg-12
      = f.button :submit, :class => 'btn-primary'
      '
      = link_to t('.cancel', :default => t("helpers.links.cancel")), question_templates_path, :class => 'btn btn-default'

br

app/views/question/question_templates/edit.html.slim
- model_class = Question::QuestionTemplate
.page-header
  h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/question/question_templates/index.html.slim
/ - model_class = Question::QuestionTemplate


/ .page-header
/   h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
/ table.table.table-striped
/   thead
/     tr
/       th= model_class.human_attribute_name(:type)
/       th= model_class.human_attribute_name(:name)
/       th=t '.actions', :default => t("helpers.actions")
/   tbody
/     - @question_templates.each do |question_template|
/       tr
/         td= link_to question_template.id, question_template_path(question_template)
/         td= question_template.type
/         td= question_template.name
/         td=l question_template.created_at
/         td
/           = link_to t('.show', :default => t("helpers.links.show")), question_template_path(question_template), :class => 'btn btn-default btn-xs'
/           '
/           / = link_to t('.edit', :default => t("helpers.links.edit")), edit_question_question_template_path(question_template), :class => 'btn btn-default btn-xs'
/           / '
/           / = link_to t('.destroy', :default => t("helpers.links.destroy")), question_question_template_path(question_template), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

/ = link_to t('.new', :default => t("helpers.links.new")), new_question_template_path, :class => 'btn btn-primary'

#app_vue

== javascript_pack_tag 'application'

app/views/question/question_templates/list.html.slim
- model_class = Question::QuestionTemplate


.page-header
  h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
table.table.table-striped
  thead
    tr
      th= model_class.human_attribute_name(:type)
      th= model_class.human_attribute_name(:name)
      th=t '.actions', :default => t("helpers.actions")
  tbody
    - @question_templates.each do |question_template|
      tr
        td= link_to question_template.id, question_template_path(question_template)
        td= question_template.type
        td= question_template.name
        td=l question_template.created_at
        td
          = link_to t('.show', :default => t("helpers.links.show")), question_template_path(question_template), :class => 'btn btn-default btn-xs'
          '
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_question_template_path(question_template), :class => 'btn btn-default btn-xs'
          / '
          / = link_to t('.destroy', :default => t("helpers.links.destroy")), question_question_template_path(question_template), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_question_template_path, :class => 'btn btn-primary'

app/views/question/question_templates/new.html.slim
- model_class = Question::QuestionTemplate
.page-header
  h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/question/question_templates/show.html.slim
- model_class = Question::QuestionTemplate
.page-header
  h1=t '.title', :default => model_class.model_name.human.titleize

p
  strong= model_class.human_attribute_name(:name) + ':'
  br
  = @question_template.name
p
  strong= model_class.human_attribute_name(:slug) + ':'
  br
  = @question_template.slug

- if @question_template.image.present?
  p
    strong= model_class.human_attribute_name(:image_file_name) + ':'
    br
    = image_tag @question_template.image.url, width: 200

p
  strong= model_class.human_attribute_name(:question_type) + ':'
  br
  = @question_template.question_type
p
  strong= model_class.human_attribute_name(:question_subtype) + ':'
  br
  = @question_template.question_subtype
p
  strong= model_class.human_attribute_name(:question_total_correct_items) + ':'
  br
  = @question_template.question_total_correct_items
p
  strong= model_class.human_attribute_name(:question_shuffle_keys) + ':'
  br
  = @question_template.question_shuffle_keys
p
  strong= model_class.human_attribute_name(:question_shuffle_values) + ':'
  br
  = @question_template.question_shuffle_values
p
  strong= model_class.human_attribute_name(:points_lost_a_star_by_attempt) + ':'
  br
  = @question_template.points_lost_a_star_by_attempt
p
  strong= model_class.human_attribute_name(:points_lost_a_star_by_time) + ':'
  br
  = @question_template.points_lost_a_star_by_time
p
  strong= model_class.human_attribute_name(:item_template_key_font_size) + ':'
  br
  = @question_template.item_template_key_font_size
p
  strong= model_class.human_attribute_name(:item_template_key_custom) + ':'
  br
  = @question_template.item_template_key_custom
p
  strong= model_class.human_attribute_name(:item_template_key_tags) + ':'
  br
  = @question_template.item_template_key_tags
p
  strong= model_class.human_attribute_name(:item_template_key_total_per_line) + ':'
  br
  = @question_template.item_template_key_total_per_line
p
  strong= model_class.human_attribute_name(:item_template_key_template_slug) + ':'
  br
  = @question_template.item_template_key_template_slug
p
  strong= model_class.human_attribute_name(:item_template_value_font_size) + ':'
  br
  = @question_template.item_template_value_font_size
p
  strong= model_class.human_attribute_name(:item_template_value_custom) + ':'
  br
  = @question_template.item_template_value_custom
p
  strong= model_class.human_attribute_name(:item_template_value_tags) + ':'
  br
  = @question_template.item_template_value_tags
p
  strong= model_class.human_attribute_name(:item_template_value_total_per_line) + ':'
  br
  = @question_template.item_template_value_total_per_line
p
  strong= model_class.human_attribute_name(:item_template_value_template_slug) + ':'
  br
  = @question_template.item_template_value_template_slug

hr

= link_to t('.back', :default => t("helpers.links.back")), question_templates_path, :class => 'btn btn-default'
'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_question_template_path(@question_template), :class => 'btn btn-default'
'
= link_to t('.destroy', :default => t("helpers.links.destroy")), question_template_path(@question_template), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

br
br