config/routes.rb
Rails.application.routes.draw do
  resources :user_games do
    get '/get_from_code/:code', to: 'user_games#get_from_code', on: :collection
  end


  authenticated :user do
    root to: 'home#index'
  end

  unauthenticated :user do
    devise_scope :user do
      get '/', to: 'devise/sessions#new'

      get '/cadastro/aluno', to: 'users/registrations#new', role: :student, as: :new_student
      get '/cadastro/professor', to: 'users/registrations#new', role: :professor, as: :new_professor
    end
  end

  devise_for :users, controllers: { registrations: 'users/registrations' }

  devise_scope :user do
    get :sair, to: 'devise/sessions#destroy'
  end

  # GAME

  namespace :game do
    post '/user_game',                                          to: 'user_games#create',   defaults: { format: :json }
    get '/user_game/me/:code',                                  to: 'user_games#me',   defaults: { format: :json }

    get '/',                                                                          to: 'modulos#index',          defaults: { format: :json }, as: :modulos
    get '/all',                                                                       to: 'modulos#all',            defaults: { format: :json }, as: :all
    get '/:modulo_slug',                                                              to: 'target_audiences#index', defaults: { format: :json }, as: :target_audiences
    get '/:modulo_slug/:target_audience_slug',                                        to: 'themes#index',           defaults: { format: :json }, as: :themes
    get '/:modulo_slug/:target_audience_slug/:theme_slug',                            to: 'units#index',            defaults: { format: :json }, as: :units
    get '/:modulo_slug/:target_audience_slug/:theme_slug/:unit_slug',                 to: 'questions#index',        defaults: { format: :json }, as: :questions
    get '/:modulo_slug/:target_audience_slug/:theme_slug/:unit_slug/:question_order', to: 'questions#show',         defaults: { format: :json }, as: :question
  end

  # GAME

  namespace :question do
    resources :types
    resources :item_templates
    resources :titles
    resources :descriptions
    resources :templates, controller: 'question_templates' do
      get :list, on: :collection
    end

    resources :questions do
      put :publish, on: :member
      put :archive, on: :member
      resources :items, controller: 'questions_items'
    end
  end

  resources :themes do
    resources :units
  end
  resources :units
  resources :theme_audiences
  resources :modulos
  resources :groups do
    resources :participants, controller: :groups_participants
  end

  resources :words
  resources :karaokes
  resources :books

  namespace :admin do
    resources :users
  end

  namespace :professor do
    resources :students
  end

  get '/pages/*id' => 'pages#show', as: :page, format: false
end

app/models/unit.rb
# Unidades.
class Unit < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :scoped, :scope => :theme

  enum status: { active: 0,
                inactive: 1 }

  belongs_to :user
  belongs_to :theme

  has_one :modulo, through: :theme

  has_many :questions, class_name: 'Question::Question'

  before_create :set_default_image

  has_attached_file :cover,
                    styles: { medium: "300x300>", thumb: "100x100>" }

  validates_attachment_content_type :cover, content_type: /\Aimage\/.*\z/

  def self.next_order
    self.maximum(:order).try(:next) || 1
  end

  def cover_full_url
    if cover.present?
      cover.url
    else
      remote_cover_url
    end
  end

  private

  def set_default_image
    self.remote_cover_url ||= [ENV['ASSET_HOST'], "images/modulos/#{modulo.slug}/#{theme.target_audience_i18n}/#{theme.slug}/#{slug}.png"].join('/')
  end
end

app/controllers/game/units_controller.rb
# Unidades de um tema.
class Game::UnitsController < ApplicationController
  skip_before_action :authenticate_user!

  before_action :set_theme, only: :index

  def index
    @units = policy_scope(@theme.units).order(:order)
  end

  private

  def set_theme
    @modulo = Modulo.friendly.find(params[:modulo_slug])
    @target_audience = ThemeAudience.friendly.find(params[:target_audience_slug])
    @theme = Theme.where(:theme_audience_id => @target_audience).friendly.find(params[:theme_slug])
  end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  before_action :set_theme
  before_action :set_unit, only: [:show, :edit, :update, :destroy]

  before_action do
    authorize Unit, :manage?
  end

  # GET /units
  def index
    @q = policy_scope(@theme.units).ransack(params[:q])
    @units = @q.result.order(:order).page(params[:page])
  end

  # GET /units/1
  def show
  end

  # GET /units/new
  def new
    @unit = @theme.units.new order: Unit.next_order
  end

  # GET /units/1/edit
  def edit
  end

  # POST /units
  def create
    @unit = @theme.units.new unit_params
    @unit.user = current_user

    if @unit.save
      redirect_to [@theme, @unit], notice: t('helpers.submit.saved')
    else
      render :new
    end
  end

  # PATCH/PUT /units/1
  def update
    if @unit.update(unit_params)
      redirect_to [@theme, @unit], notice: t('helpers.submit.saved')
    else
      render :edit
    end
  end

  # DELETE /units/1
  def destroy
    @unit.destroy
    redirect_to theme_units_url(@theme), notice: t('helpers.submit.destroyed')
  end

  private

  def set_theme
    @theme = Theme.friendly.find(params[:theme_id])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_unit
    @unit = @theme.units.friendly.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def unit_params
    params.require(:unit).permit(:theme_id,
                                 :status,
                                 :order,
                                 :title,
                                 :description,
                                 :cover)
  end
end

app/views/units/_filter.html.slim
= search_form_for @q, builder: SimpleForm::FormBuilder do |f|

  .row
    .col-lg-4
      = f.input :title_cont, label: 'Título', required: false, wrapper: :horizontal_form

    .col-lg-4
      = f.input :order_eq, label: 'Ordem', required: false, wrapper: :horizontal_form

    .col-lg-4
      = f.submit 'Filtrar', class: 'btn btn-primary'

hr

app/views/units/_form.html.slim
- url = @unit.persisted? ? theme_unit_path(@theme, @unit) : theme_units_path(@theme)

= simple_form_for @unit, url: url do |f|

  .row
    .col-lg-6
      = f.association :theme, include_blank: false

  .row
    .col-lg-2
      = f.input :order

    .col-lg-4
      = f.input :title

  .row
    .col-lg-6
      = f.input :description
    .col-lg-2
      = f.input :status

  .row
    .col-lg-6
      = f.input :cover, as: :file

  hr

  .row
    .col-lg-12
      = f.button :submit, :class => 'btn-primary'
      '
      = link_to t('.cancel', :default => t("helpers.links.cancel")), theme_units_path(@theme), :class => 'btn btn-default'

app/views/units/edit.html.slim
- model_class = Unit
.page-header
  h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/units/index.html.slim
- model_class = Unit
.page-header
  h1=t '.title', :default => model_class.model_name.human.pluralize.titleize

= render partial: 'filter'

.panel.panel-default
  .panel-heading
    .row
      .col-lg-6
        ' Registros:
        b= @units.count

      .col-lg-6
        .text-right
          = link_to t('.new', :default => t("helpers.links.new")), new_theme_unit_path(@theme), :class => 'btn btn-primary btn-xs'

  .panel-body
    table.table.table-striped
      thead
        tr
          th= model_class.human_attribute_name(:order)
          th= model_class.human_attribute_name(:title)
          th= model_class.human_attribute_name(:status)
          th= model_class.human_attribute_name(:theme)
          th= model_class.human_attribute_name(:questions)
          th=t '.actions', :default => t("helpers.actions")
      tbody
        - @units.each do |unit|
          tr
            td= unit.order
            td= link_to unit.title, theme_unit_path(@theme, unit)
            td= unit.status
            td= unit.theme.title
            td= link_to unit.questions.count, question_questions_url(q: { modulo_id_eq: @theme.modulo.id, theme_id_eq: @theme.id, unit_id_eq: unit.id })
            td
              = link_to t('.show', :default => t("helpers.links.show")), theme_unit_path(@theme, unit), :class => 'btn btn-default btn-xs'
              '
              = link_to t('.edit', :default => t("helpers.links.edit")), edit_theme_unit_path(@theme, unit), :class => 'btn btn-default btn-xs'
              '
              = link_to "Nova atividade", question_templates_path(:unit_id => unit.id), :class => 'btn btn-primary btn-xs'

= link_to t('.back', :default => t("helpers.links.back")), themes_path, :class => 'btn btn-default'

app/views/units/new.html.slim
- model_class = Unit
.page-header
  h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/units/show.html.slim
- model_class = Unit
.page-header
  h1=t '.title', :default => model_class.model_name.human.titleize

.row
  .col-lg-12
    p
      strong= model_class.human_attribute_name(:order) + ':'
      br
      = @unit.order
    p
      strong= model_class.human_attribute_name(:theme) + ':'
      br
      = @unit.theme.title
    p
      strong= model_class.human_attribute_name(:title) + ':'
      br
      = @unit.title
    p
      strong= model_class.human_attribute_name(:description) + ':'
      br
      = @unit.description

    - if @unit.cover.present?
      p
        strong= model_class.human_attribute_name(:cover) + ':'
        br
        = image_tag @unit.cover.url(:thumb)

    - if @unit.remote_cover_url.present?
      p
        strong= model_class.human_attribute_name(:cover) + ':'
        br
        = image_tag @unit.remote_cover_url, width: 200

hr

.row
  .col-lg-12
    = link_to t('.back', :default => t("helpers.links.back")), theme_units_path(@theme), :class => 'btn btn-default'
    '
    = link_to t('.edit', :default => t("helpers.links.edit")), edit_theme_unit_path(@theme, @unit), :class => 'btn btn-default'
    '
    = link_to t('.destroy', :default => t("helpers.links.destroy")), theme_unit_path(@theme, @unit), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

br